trigger: none
#  branches:
#    include:
#    - main

variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'iac-demo'
  location: 'canadacentral'
  paramFile: 'projects/sample/iac-bicep/iac-bicep-webapp/parameters/network.dev.bicepparam'
  templateFile: 'projects/sample/iac-bicep/iac-bicep-webapp/src/network.bicep'
  
pool:
  vmImage: $(vmImageName)

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy Azure BiCEP Infrastructure
    environment: 
      name: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Preview Bicep Changes
            inputs:
              azureSubscription: 'Subscritpion1'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az --version
                az upgrade --yes
                echo "Deploy Bicep template"
                pwd
                echo "Check listing"
                ls -lrt
                az deployment group create --resource-group $(resourceGroupName) \
                  --template-file $(templateFile) \
                  --parameters $(paramFile)